### PR TITLE
feat: make all keyboard shortcuts configurable

### PR DESCRIPTION
**Pull request by JoJowAkaGioGiow**
## Summary

- Makes app actions, terminal search, and the three PTY translations visible and configurable in Settings > Hotkeys.
- Supports rebinding, per-action reset, disabling, and a persistent unassigned state.
- Keeps keyboard zoom outside Settings as a fixed physical-key accelerator, including numpad and dedicated plus/minus layout support.
- Updates the shortcuts overlay to display every configurable action's active binding, including unassigned actions.

## Behavior and safety

- Applies shortcut changes to live terminals without respawning their PTYs.
- Uses Ctrl on Linux and Windows, Cmd on macOS, and literal Control where terminal actions require it.
- Keeps Ctrl+V as the only physical clipboard-image binding on every platform. Windows translates that press internally to the ESC v sequence Claude Code expects; there is no Alt+V default or alternate.
- Rejects truly bare recorded or persisted bindings for every action. Ctrl/Cmd, literal Control, Shift, or Alt each satisfy the modifier requirement, so Shift+Enter remains valid.
- Validates known persisted overrides without write-on-read side effects. Retired zoom keys are unknown and ignored in memory until the next normal save serializes the current shape.
- Detects conflicts between configurable actions while ignoring unassigned bindings. At most one lich action handles a press; the first successful window listener wins, and React mount/registration order is deliberately not treated as a stable priority.
- Keeps fixed zoom on Ctrl/Cmd plus physical Equal, Minus, and 0, including numpad keys and a character fallback for layouts with dedicated plus/minus keys. `claimHotkey` still prevents double execution when a configurable rebind collides with zoom.
- Keeps dangerous Chromium close, Find, and zoom accelerators guarded independently without stopping propagation. Meta+brackets are guarded only on macOS, Alt+arrows only off macOS, AltGr remains free, and Alt+F4 is not claimed.
- Preserves key repeat for PTY translations while keeping discrete global actions single-shot.

## Verification

- Focused shortcut contracts: 6 files, 77 tests passed.
- Full frontend suite: 95 files, 1,123 tests passed.
- Frontend coverage: 96.65% statements, 97.18% branches, 94.62% functions, and 96.67% lines.
- `pnpm check` completed with no errors (13 existing warnings), and `pnpm build` succeeded.
- Go formatting and vet passed; backend tests: 1,968 passed, 0 failed, 85.9% coverage.
- Real `task dev` smoke: Zoom In/Out/Reset were absent from Settings and the overlay; Attach clipboard image displayed Ctrl+V with no Alt+V alternate; bare `a` stayed in capture while Shift+Enter recorded; terminal-focused Ctrl+Equal changed app zoom from 100% to 110%, Ctrl+Minus/Ctrl+0 returned it to 100%; Ctrl+/ still opened the shortcuts overlay from the terminal.
- Windows clipboard translation was verified by the `windows=true` contract: physical Ctrl+V emits ESC v while Alt+V falls through.

### CODE REVIEW

File: frontend/src/lib/hotkeys.ts [hunk 1]
```diff
@@ -27,270 +20,354 @@ export type HotkeyId =
...
+  key,
+})
+
+const imageCombo = (windows: boolean): Combo =>
+  windows ? combo(false, false, true, "v") : combo(false, false, false, "v", true)
+
+// Defaults avoid Ctrl+letter where a shifted chord is available: every bound
+// global combo is captured before xterm and therefore belongs to lich, not the
+// TUI. Terminal translations are deliberate exceptions because their action is
+// the sequence lich writes to the PTY.
```
Comment (omartelo) [inline frontend/src/lib/hotkeys.ts]: This four line comment replaces about forty that recorded what each default chord costs the TUI underneath, measured by pressing it into `cat -v` in a live session: Ctrl+letter is a control code the shell already binds, Ctrl+Shift+letter reaches the PTY as nothing at all, Ctrl+Shift+arrow arrives as a real CSI sequence so it does cost something, Ctrl+Alt+arrow never arrives on Linux.

The defaults in this file did not change in this PR, so nothing in the diff makes that record obsolete. It is the only place that knowledge is written down, and without it the next person picking a default has to redo the measurement.

Same deletion in three other files: the header of `zoom-keys.ts` on why zoom is matched on the physical key, the header of `browser-defaults.ts` listing which accelerators are fatal in an `--app` window and why AltGr forces Alt out of the matcher, and the header of `term-keys.ts` on what xterm encodes wrong for each of the three sequences.

Please restore all four. If a comment went stale because the code moved under it, rewrite that part, but do not drop the reasoning.

File: frontend/src/lib/hotkeys.ts [hunk 2]
```diff
@@ -27,270 +20,354 @@ export type HotkeyId =
...
+const combo = (mod: boolean, shift: boolean, alt: boolean, key: string, ctrl = false): Combo => ({
+  mod,
+  ctrl,
+  shift,
+  alt,
+  key,
+})
+
+const imageCombo = (windows: boolean): Combo =>
+  windows ? combo(false, false, true, "v") : combo(false, false, false, "v", true)
```
Comment (omartelo) [inline frontend/src/lib/hotkeys.ts]: I want the reasoning behind this one. You are right that Claude Code binds Alt+V on Windows, I checked it, so the concern is not accuracy.

It is that lich is not only used by developers. A user who is not one already knows Ctrl+V as paste, and lich has been giving them that everywhere. On Linux and macOS Ctrl+V is the image attach precisely because the terminal's own text paste is Ctrl+Shift+V, so the chord is free and lich standardizes on it across platforms. Making Windows the one place where the same action needs a different key trades that standardization for a chord the user has to learn, and the non-developers pay that cost first.

What I do want is for Alt+V to keep working, so somebody coming from Claude Code in a terminal finds their muscle memory intact. So: Ctrl+V stays the Windows default, and Alt+V is an addition rather than a replacement.

That does sit against this PR's own goal, since a second chord that is not a row in Settings is a binding nobody can see or rebind. You reshaped this module, so tell me how you would rather express it: a second binding on that row, a Windows-only alternate that Settings shows as read only, or something else. I am not attached to a mechanism, only to Ctrl+V still working there.

File: frontend/src/lib/hotkeys.ts [hunk 3]
```diff
@@ -27,270 +20,354 @@ export type HotkeyId =
...
+
+export function comboFromEvent(
+  event: KeyState,
+  mac = isMac,
+  allowUnmodified = false,
+): Combo | null {
+  if (MODIFIER_KEYS[event.key] || (event.ctrlKey && event.metaKey)) return null
+  const mod = mac ? event.metaKey : event.ctrlKey
+  const ctrl = mac && event.ctrlKey
+  if (!mod && !ctrl && !event.altKey && !allowUnmodified) return null
```
Comment (omartelo) [inline frontend/src/lib/hotkeys.ts]: This lets a bare letter be recorded on any row that sets `allowUnmodified`, and all three terminal rows do. Checked against the real code:

```ts
const recorded = comboFromEvent(k({ key: "a" }), false, true)
// {mod:false, ctrl:false, shift:false, alt:false, key:"a"}
chordSequence(k({ key: "a" }), { ...defaultHotkeys(false), attachClipboardImage: recorded }, false, false)
// "\x16"
```

After that, every `a` typed into any terminal is swallowed and sent as SYN. It is recoverable, Settings is still reachable, but nothing on screen tells the user what happened.

The root cause is one line up: `shift` is not counted as a modifier, so `Shift+Enter` gets rejected and `allowUnmodified` was added to let it through. All three terminal defaults already carry a modifier (Ctrl+Backspace, Ctrl/Alt+V, Shift+Enter). Count shift in this check and `allowUnmodified` goes away entirely, along with the field on `HotkeyAction` and the third parameter here. That closes the hole and removes code.

This also needs a line in `docs/ceilings.md`: a rebind is checked against conflicts with other lich actions and against nothing else, so it can still take a chord the TUI needs, and on the terminal rows it can take a plain character.

File: frontend/src/lib/terminal/zoom-keys.ts [hunk 4]
```diff
@@ -1,57 +1,11 @@
...
-  if (event.altKey) return null
-  const byChar = ZOOM_CHARS[event.key]
-  if (byChar) return byChar
-  if (event.shiftKey && event.code !== SHIFTABLE_CODE) return null
-  return ZOOM_CODES[event.code] ?? null
+export function zoomIntent(event: KeyState, hotkeys: Hotkeys, mac = isMac): ZoomIntent | null {
+  if (matchesRepeatingCombo(event, hotkeys.zoomIn, mac)) return "in"
+  if (matchesRepeatingCombo(event, hotkeys.zoomOut, mac)) return "out"
+  if (matchesCombo(event, hotkeys.zoomReset, mac)) return "reset"
+  return null
```
Comment (omartelo) [inline frontend/src/lib/terminal/zoom-keys.ts]: This is a revert of #68 and the PR description does not mention it. That PR moved zoom off the configurable list on purpose and matched it on `event.code`, because a browser accelerator answers to a physical key and not to a character. The bug it fixed was the app and Chromium both zooming at once on Ctrl+plus.

I traced the new matcher and it does hold for the layouts that mattered: `normalizeKey` folding `=` into `+` plus `normalizedShift` covers US and ABNT2, and the German dedicated plus key arrives as the character anyway. So this is not broken. What I want to know is why you preferred it, because two things get lost: the numpad with NumLock off, where `Numpad0` arrives as `Insert` and no longer resets zoom, and the property that the chord lich claims is the same physical key Chromium claims.

If the answer is that zoom has to be configurable for the feature to be complete and character matching is the price, I can live with that, but then it belongs in the PR body and in `docs/ceilings.md` as a deliberate trade, and the NumLock case has to be either handled or written down.

File: frontend/src/lib/hotkeys.ts [hunk 5]
```diff
@@ -301,52 +378,78 @@ function formatKey(key: string): string {
...
+    const parsed = parsedCombo(value)
+    if (
+      id === "terminalSearch" &&
+      parsed &&
+      !parsed.mod &&
+      !parsed.ctrl &&
+      !parsed.shift &&
+      !parsed.alt
+    ) {
+      continue
```
Comment (omartelo) [inline frontend/src/lib/hotkeys.ts]: This drops a stored binding with no modifiers, but only for `terminalSearch`. The same stored value is just as bad on any other row that did not opt into bare keys, and if the `comboFromEvent` fix above lands it is bad on the terminal rows too.

Make it a rule rather than a case: reject a parsed binding with no modifier unless the action opted in.

File: frontend/src/lib/browser-defaults.ts [hunk 6]
```diff
@@ -1,69 +1,73 @@
...
-  if (!mod || event.altKey) {
-    return false
+  if (mod && !event.altKey) {
+    return event.shiftKey ? MOD_SHIFT_KEYS[key] === true : MOD_KEYS[key] === true
   }
-  const key = event.key.toLowerCase()
-  return event.shiftKey ? MOD_SHIFT_KEYS.has(key) : MOD_KEYS.has(key)
+  if (!mod && event.altKey && !event.shiftKey) {
+    return key === "arrowleft" || key === "arrowright" || key === "f4"
+  }
```
Comment (omartelo) [inline frontend/src/lib/browser-defaults.ts]: Two things.

`Alt+F4` is the window manager on Linux and Windows, not Chromium. `preventDefault` in the renderer does not stop it, so that arm never does anything. `[` and `]` are back and forward on macOS only; on Linux and Windows those are Alt+Left and Alt+Right, which this branch already covers, so blocking the brackets everywhere costs Ctrl+[ for no gain. It still works, because this guard only calls `preventDefault` and xterm reads the event afterwards, but it reads as if someone measured it and nobody did.

Blocking `f` and the zoom keys is the right call and I want to be explicit about that: those rows are disableable now, so the guard has to stand on its own. That part I would keep exactly as it is.

Separately, switching `Set` to `Record<string, true>` is churn. Lookup was never a bottleneck and the sets read better. Please put them back.

File: docs/ceilings.md [hunk 7]
```diff
@@ -66,13 +66,20 @@ work when nobody knows it and that the call site never shows. The mechanism and
...
-  bindings are a `lich.hotkeys` entry in localStorage, which the theme left for the workspace database precisely
-  because a recreated Chromium profile drops it: the combos revert to the defaults, and both the overlay and
-  Settings then show those defaults as if nothing had ever been rebound.
+- **A global hotkey is taken from the agent, and its rebind lives only in the
+  page** (`frontend/src/lib/use-hotkey.ts`, `hotkeys.ts`): assigned app actions
+  are caught in the window capture phase and stopped there, so the chord never
+  reaches the PTY. Terminal translations differ: xterm matches their bindings
+  and writes a substitute sequence to the PTY. Settings detects conflicts
+  between lich actions; on a conflicting keypress, the first successful handler
+  claims it, while a handler that is unavailable leaves it for the next one.
```
Comment (omartelo) [inline docs/ceilings.md]: "the first successful handler claims it" is accurate but leaves out which one is first. The claim goes to whichever window listener runs first, which is registration order, which is React mount order. `TerminalView` mounts and unmounts as sessions come and go, so on a conflict involving terminal search the winner can change between one press and the next.

Settings shows the conflict, so the user is not blind, but the ceiling should say the order is not stable rather than imply a priority exists.

File: frontend/src/lib/terminal/zoom-keys.test.ts [hunk 8]
```diff
@@ -1,70 +1,54 @@
...
+    }
+    expect(zoomIntent(press({ ctrlKey: true, shiftKey: true, key: "i" }), hotkeys, false)).toBe(
+      "in",
+    )
+    expect(zoomIntent(press({ ctrlKey: true, key: "+" }), hotkeys, false)).toBeNull()
+  })
+
+  it("returns no intent when a zoom action is unassigned", () => {
+    const hotkeys = { ...defaultHotkeys(false), zoomReset: null }
+    expect(zoomIntent(press({ ctrlKey: true, key: "0" }), hotkeys, false)).toBeNull()
```
Comment (omartelo) [inline frontend/src/lib/terminal/zoom-keys.test.ts]: The rewrite dropped the cases that pinned the old behavior: numpad, the German layout fallback, Alt being ignored so Alt chords reach the PTY, and shifted chords other than Equal not being claimed. I checked the new matcher and it still gets all of those right except NumLock-off numpad, so this is not a behavior regression, but nothing holds them anymore.

Same in `term-keys.test.ts`, where `leaves Ctrl+Shift+V alone` and the case-insensitive `V` cases went away, and in `hotkeys.test.ts`, where `rejects when a modifier differs` and `rejects a different key` went away.

A test changes for one of two reasons: the contract changed, or the test asserted something the contract never promised. Name which one applies per case, or bring the assertions back against the new signatures.

**Review by omartelo — COMMENTED** [review]
Thanks for this. It is a big and careful PR, and it does what the title says. I pulled the branch and the gate is green here too: 89 test files, 1025 tests, coverage 95.77 / 96.50 / 93.15 / 95.80, biome and tsc clean, vite build fine. No Go files touched, so the backend is a no-op.

Most of what follows is not about whether the feature should exist. Making every binding configurable is a good goal, and the Terminal group in the shortcuts overlay is a real improvement over the hardcoded passthrough rows. What I want settled before merging is four things: one that has to be restored, one that has to be fixed, and two decisions I want you to justify rather than have me guess at.

1. The rationale comments have to come back. They are the record of measurements that cost real work.
2. `allowUnmodified` opens a way to make a terminal unusable. That needs a fix and a ceilings note.
3. Zoom moving from `event.code` back to `event.key` reverts a decision from #68. Tell me why.
4. Windows image attach moving from Ctrl+V to Alt+V. I want the reasoning, and I want Ctrl+V to stay the default there.

Details inline. Nothing here is a rewrite request, the shape of the feature is right.

File: frontend/src/lib/hotkeys.ts (hunk 1 above)
Comment (JoJowAkaGioGiow) [reply frontend/src/lib/hotkeys.ts]: Restored the measured rationale in `hotkeys.ts`, `zoom-keys.ts`, `browser-defaults.ts`, and `term-keys.ts`, adapting only the behavior that moved.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

File: frontend/src/lib/hotkeys.ts (hunk 2 above)
Comment (JoJowAkaGioGiow) [reply frontend/src/lib/hotkeys.ts]: Kept Ctrl+V as the only physical binding on Windows; lich still translates it internally to ESC v there, and there is no Alt+V default or alternate.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

File: frontend/src/lib/hotkeys.ts (hunk 3 above)
Comment (JoJowAkaGioGiow) [reply frontend/src/lib/hotkeys.ts]: Removed allowUnmodified; Shift now satisfies the modifier requirement, while bare keys are rejected.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

File: frontend/src/lib/terminal/zoom-keys.ts (hunk 4 above)
Comment (JoJowAkaGioGiow) [reply frontend/src/lib/terminal/zoom-keys.ts]: Reverted zoom to the physical-key design from #68; zoom is no longer a configurable Hotkey, and code matching restores numpad and layout behavior.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

File: frontend/src/lib/hotkeys.ts (hunk 5 above)
Comment (JoJowAkaGioGiow) [reply frontend/src/lib/hotkeys.ts]: Generalized persisted binding validation to every action; every non-null combo needs Ctrl/Cmd, literal Control, Shift, or Alt.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

File: frontend/src/lib/browser-defaults.ts (hunk 6 above)
Comment (JoJowAkaGioGiow) [reply frontend/src/lib/browser-defaults.ts]: Restored Sets and corrected the platform guards: no Alt+F4 claim, brackets only on macOS, Alt+arrows only off macOS, with Find and zoom still independently protected.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

File: docs/ceilings.md (hunk 7 above)
Comment (JoJowAkaGioGiow) [reply docs/ceilings.md]: Documented registration-order precedence as unstable; mount order decides the winner and TerminalView remounts can change it.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

File: frontend/src/lib/terminal/zoom-keys.test.ts (hunk 8 above)
Comment (JoJowAkaGioGiow) [reply frontend/src/lib/terminal/zoom-keys.test.ts]: Restored the dropped behavioral contracts for physical zoom, terminal passthrough/case handling, and hotkey modifier/key mismatches.

Verification: 6 focused files / 77 tests; full frontend 95 files / 1,123 tests with 96.67% line coverage; backend 1,968 tests with 85.9% coverage.

**Comment by omartelo** [comment]
Thanks for this — it is a genuinely good PR, and it was a pleasure to review. The tests in particular are better than most of what lands here: corrupt JSON, unknown keys, the legacy-combo migration, bare-key rejection, unassigned rows, both sides of a conflict, and `claimHotkey` racing zoom in *both* orders. That last one is the kind of case people usually only write after it bites them in production. `docs/ceilings.md` and the `CHANGELOG.md` `[Unreleased]` entry being in the same PR is exactly the house rule, and you got there without being asked.

I ran the full local gate on your head and it is green, so what follows is not a pile of breakage — it is mostly the cost of the branch having gone stale, plus two behaviour changes I would like reconsidered. Detailed review in the next comment.

**Comment by omartelo** [comment]
Here is the review. Everything below was measured on your head (`533f1af`) or on a local test-merge with `main`, not guessed — where I say something breaks, I ran it.

## What is already right

The gate is green on your branch as it stands: `gofmt` and `go vet` clean (no Go touched, so no `api-types.ts` mirror to move), `LICH_LISTEN_PORT= go test ./...` 1968 passing, `tsc -b --noEmit` clean, `vite build` fine, `vitest` 1123 passing across 95 files, and biome reporting only the 13 warnings that are the repo's standing a11y backlog. Coverage on the files you touched comes out at **97.7% statements / 97.7% branches** — well past the 80% bar, and it is real coverage of the bad paths rather than of the happy one.

The design decisions are good ones too. Splitting literal `ctrl` out of the platform-primary `mod` is the right fix for the thing `shortcuts.ts` used to work around with hand-spelled rows, and it means `formatCombo` no longer has to lie about `⌘` on macOS. `claimHotkey` solves a real problem — `stopPropagation` genuinely does not suppress sibling listeners on `window`, so "at most one lich action per press" needed somewhere to live, and a `WeakSet` keyed on the event is the cheapest place for it.

## The branch needs a rebase — three things break after the merge

You are 29 commits behind `main`, and the split-panes work (#407, #419) landed in the same files. I merged locally to see what actually happens; `hotkeys.ts` auto-merges *cleanly* and then fails, which is the worst kind, so it is worth walking through.

**`frontend/src/lib/hotkeys.ts:44` — the two new split combos need the `ctrl` field.** `Combo` now requires `ctrl`, but `main`'s `splitBeside` and `otherPane` entries are still written as the old four-field literal. Git merges them in without complaint and `tsc` then reports two `TS2741: Property 'ctrl' is missing`. Two-line fix — run them through your own helper:

```ts
combo: combo(true, true, false, "g"),   // splitBeside
combo: combo(true, true, false, "f"),   // otherPane
```

The upside of the required field is that this *cannot* be missed silently, which is the behaviour you want.

**`frontend/src/components/TerminalView.tsx:498` — keep `focusedRef`, not `visibleRef`.** This one is a real conflict rather than a textual one, and resolving it in your branch's favour would quietly reintroduce a bug #419 just fixed. Before split panes, "visible" and "focused" were the same thing because exactly one terminal was on screen. They are not the same any more: a split paints two terminals at once, so with `visibleRef.current` **both** of them answer the search chord and the find box opens on the pane nobody is typing into. Take `main`'s `focusedRef.current` and keep your `isRecordingTarget` + `shouldOpenTerminalSearch` conditions around it.

**`frontend/src/components/render-budget.test.tsx:89` — the `localStorage` stub needs `clear()`.** Your `vi.stubGlobal` shim has `getItem`/`setItem`/`removeItem`, and #419 added a `localStorage.clear()` to that suite's `beforeEach` (the split is a pref now, so a test that opens one has to hand the next test an undivided stage). After the merge all five render-budget tests fail with `localStorage.clear is not a function`. One line.

`CHANGELOG.md` also conflicts, but that is the ordinary tax on every parallel PR here — nothing to think about.

## Two behaviour changes I would like reconsidered

**`frontend/src/lib/terminal/term-keys.ts:39` — the `event.code === "KeyV"` fallback is gone.** `main` matched Ctrl+V as `event.code === "KeyV" || event.key.toLowerCase() === "v"`, and the old `TermKeyState` carried an optional `code` for exactly that. The new `KeyState` has no `code`, so `chordSequence` never sees it and the match is on the character alone. On a Cyrillic, Greek or Hebrew layout Ctrl+V arrives with `event.key` set to a non-Latin character, so image attach in Claude Code stops working — silently, with nothing on screen to connect it to the layout. I would restore the fallback and pin it with a test that can only pass through the `code` path:

```ts
expect(chordSequence(key({ ctrlKey: true, key: "м", code: "KeyV" }), hotkeys, false, false)).toBe("\x16")
```

I realise this sits awkwardly with a configurable binding, where the user's stored combo is a character. A reasonable shape is to keep the character match as the general rule and special-case the *default* Ctrl+V on `code` — the `ceilings.md` bullet is the right place to say so in one sentence.

**`frontend/src/lib/hotkeys.ts:316` — `comboFromEvent` now accepts a Shift-only printable chord.** `main` returned `null` unless a primary modifier or Alt was held; you relaxed it to `if (!mod && !ctrl && !event.shiftKey && !event.altKey) return null`. That relaxation is genuinely needed — `insertTerminalNewline` defaults to Shift+Enter and could not otherwise be recorded — but it reaches further than the case that needed it. I checked, and this round-trips:

```ts
comboFromEvent({ shiftKey: true, key: "A", ... }, false)
// → { mod: false, ctrl: false, shift: true, alt: false, key: "a" }
```

It survives `mergeHotkeys` (the bare-key guard only rejects a combo with *no* modifier at all), and `matchesCombo` then matches it. Bind that to a global action and `useHotkey` — window capture phase, `preventDefault` + `stopPropagation` — eats every capital A in the app, terminal included. The user can still reach Settings to undo it, because recording bypasses the guard, but they cannot type an `A` anywhere until they do.

The narrow fix keeps everything you need: reject a Shift-only combo when the key is a single printable character, and let Shift+Enter, Shift+Tab, Shift+Arrow and the rest through, since none of those is a character anyone types.

## Smaller things

**Restore the rationale comments, and let the diff be the feature.** A large share of the 879/671 is rewording rather than change, and some of what went with it was expensive to learn: why `event.code` is the real answer for a physical key rather than a character (`normalizeKey`), why `comboKey`'s `|` separator cannot collide, what `Ctrl+Shift+P`/`O`/`Q` actually do in Chromium (`browser-defaults.ts`), and why `UNASSIGNED` is how a user hands a chord back to the TUI. The house rule is comments for the *why*, and those were all why. Keeping them also makes the review shorter, which helps you as much as me.

**`frontend/src/lib/browser-defaults.ts:14` deserves its own paragraph in the PR body.** Adding `q l f + = - 0` to `MOD_KEYS`, `+ =` to `MOD_SHIFT_KEYS`, and the macOS `Cmd+[`/`]` and Alt+arrow guards is not incidental — it is *load-bearing* for the rest of the design. It is what lets the zoom handler in `settings.tsx` bail on a lost `claimHotkey` without Chromium's own zoom firing on top, which is precisely the double-zoom the old comment there warned about. I convinced myself it holds (numpad included, since `NumpadAdd`/`Numpad0` still report `+`/`0` in `event.key`), but a reader should not have to re-derive that. Say it out loud, in the comment above the set.

**The `docs/ceilings.md` bullet understates the Shift-only case.** The bullet is otherwise excellent — naming the listener-order trap ("follows React registration and mount order, not a stable action priority") is exactly the kind of thing that file exists for, and I would not have thought to write it. But it says a *terminal translation* rebound to `Shift+A` can steal the printable `A`. Every global action can too, and there the chord is also `stopPropagation`'d, so the terminal never sees it at all. If you take the `comboFromEvent` fix above, most of that sentence can just go away.

Two nits, take or leave: `hotkeys.ts:250` turns `MODIFIER_KEYS` from a `Set` into a bare object literal, which makes `MODIFIER_KEYS["constructor"]` truthy — unreachable with real `event.key` values, but the `Set` had no such edge and the change buys nothing. And `HotkeysSettings.tsx:36`: off macOS `comboFromEvent` always yields `ctrl: false`, so hand-recording a terminal default (stored as `ctrl: true, mod: false`) never `sameCombo`s it and the Reset button stays lit. Purely cosmetic — `hotkeyConflicts` already normalises the two forms correctly, which was nice to see.

## Checklist

- [ ] **a.** Rebase on `main`.
- [ ] **b.** Add `ctrl` to the merged `splitBeside` / `otherPane` combos (`hotkeys.ts`).
- [ ] **c.** Keep #419's `focusedRef` in the `TerminalView` search gate.
- [ ] **d.** Add `clear()` to the `localStorage` stub in `render-budget.test.tsx`.
- [ ] **e.** Restore the `event.code === "KeyV"` fallback, with a `key: "м"` test.
- [ ] **f.** Reject Shift-only combos whose key is a single printable character.
- [ ] **g.** Put the deleted rationale comments back and drop the unrelated rewording.

Only a–f are blocking. Thanks again — this is careful work, and the parts I am pushing back on are narrow.
